### ISSUE TITLE
Running axe-cli in AWS Lambda

### ISSUE THREAD

**Issue by jaimeiniesta** [jaimeiniesta/axe-cli-lambda-http#1]
Hi @stephenmathieson - as a continuation of https://github.com/jaimeiniesta/axe-core-lambda-http/issues/1 I'm trying to do a version of this AWS Lambda that instead of using Puppeteer (that crashes on some URLs), instead uses `axe-cli` directly.

So far, the code in this repo works great in development but I'm not able to run it in AWS Lambda:

```
  Feb 21st 04:30:32pm INFO staging 80234df request: id=a084f4c0-35ed-11e9-94f9-fb260b8771eb ip=83.55.33.179 method=GET path=/ query=url=http%3A%2F%2Fwww.ulsla.min-saude.pt%2F
  Feb 21st 04:30:33pm ERRO staging 80234df /var/task/node_modules/selenium-webdriver/lib/promise.js:2626
  Feb 21st 04:30:33pm ERRO staging 80234df         throw error;
  Feb 21st 04:30:33pm ERRO staging 80234df         ^
  Feb 21st 04:30:33pm ERRO staging 80234df
  Feb 21st 04:30:33pm ERRO staging 80234df Error: Server terminated early with status 126
  Feb 21st 04:30:33pm ERRO staging 80234df     at earlyTermination.catch.e (/var/task/node_modules/selenium-webdriver/remote/index.js:252:52)
  Feb 21st 04:30:33pm ERRO staging 80234df     at <anonymous>
  Feb 21st 04:30:33pm ERRO staging 80234df     at process._tickCallback (internal/process/next_tick.js:188:7)
  Feb 21st 04:30:33pm ERRO staging 80234df From: Task: WebDriver.createSession()
  Feb 21st 04:30:33pm ERRO staging 80234df     at Function.createSession (/var/task/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
  Feb 21st 04:30:33pm ERRO staging 80234df     at Function.createSession (/var/task/node_modules/selenium-webdriver/chrome.js:761:15)
  Feb 21st 04:30:33pm ERRO staging 80234df     at createDriver (/var/task/node_modules/selenium-webdriver/index.js:170:33)
  Feb 21st 04:30:33pm ERRO staging 80234df     at Builder.build (/var/task/node_modules/selenium-webdriver/index.js:642:16)
  Feb 21st 04:30:33pm ERRO staging 80234df     at startDriver (/var/task/node_modules/axe-cli/lib/webdriver.js:35:26)
  Feb 21st 04:30:33pm ERRO staging 80234df     at testPages (/var/task/node_modules/axe-cli/lib/axe-test-urls.js:11:10)
  Feb 21st 04:30:33pm ERRO staging 80234df     at Object.<anonymous> (/var/task/node_modules/axe-cli/index.js:130:1)
  Feb 21st 04:30:33pm ERRO staging 80234df     at Module._compile (module.js:652:30)
  Feb 21st 04:30:33pm ERRO staging 80234df     at Object.Module._extensions..js (module.js:663:10)
  Feb 21st 04:30:33pm ERRO staging 80234df     at Module.load (module.js:565:32)
  Feb 21st 04:30:33pm ERRO staging 80234df Runtime error { error: 'Command failed: ./node_modules/axe-cli/axe-cli -j http://www.ulsla.min-saude.pt/\n/var/task/node_modules/selenium-webdriver/lib/promise.js:2626\n        throw error;\n        ^\n\nError: Server terminated early with status 126\n    at earlyTermination.catch.e (/var/task/node_modules/selenium-webdriver/remote/index.js:252:52)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)\nFrom: Task: WebDriver.createSession()\n    at Function.createSession (/var/task/node_modules/selenium-webdriver/lib/webdriver.js:769:24)\n    at Function.createSession (/var/task/node_modules/selenium-webdriver/chrome.js:761:15)\n    at createDriver (/var/task/node_modules/selenium-webdriver/index.js:170:33)\n    at Builder.build (/var/task/node_modules/selenium-webdriver/index.js:642:16)\n    at startDriver (/var/task/node_modules/axe-cli/lib/webdriver.js:35:26)\n    at testPages (/var/task/node_modules/axe-cli/lib/axe-test-urls.js:11:10)\n    at Object.<anonymous> (/var/task/node_modules/axe-cli/index.js:130:1)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n',
  Feb 21st 04:30:33pm ERRO staging 80234df   stack: 'Error: Command failed: ./node_modules/axe-cli/axe-cli -j http://www.ulsla.min-saude.pt/\n/var/task/node_modules/selenium-webdriver/lib/promise.js:2626\n        throw error;\n        ^\n\nError: Server terminated early with status 126\n    at earlyTermination.catch.e (/var/task/node_modules/selenium-webdriver/remote/index.js:252:52)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)\nFrom: Task: WebDriver.createSession()\n    at Function.createSession (/var/task/node_modules/selenium-webdriver/lib/webdriver.js:769:24)\n    at Function.createSession (/var/task/node_modules/selenium-webdriver/chrome.js:761:15)\n    at createDriver (/var/task/node_modules/selenium-webdriver/index.js:170:33)\n    at Builder.build (/var/task/node_modules/selenium-webdriver/index.js:642:16)\n    at startDriver (/var/task/node_modules/axe-cli/lib/webdriver.js:35:26)\n    at testPages (/var/task/node_modules/axe-cli/lib/axe-test-urls.js:11:10)\n    at Object.<anonymous> (/var/task/node_modules/axe-cli/index.js:130:1)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n\n    at checkExecSyncError (child_process.js:601:13)\n    at execSync (child_process.js:641:13)\n    at analyze (/var/task/app.js:13:15)\n    at Server.createServer (/var/task/app.js:33:3)\n    at emitTwo (events.js:126:13)\n    at Server.emit (events.js:214:7)\n    at parserOnIncoming (_http_server.js:619:12)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)' }
```

My idea is to execute `axe-cli` with `execSync` - maybe there's a simpler approach but this works fine in my machine, it's just that I can't get it work in AWS lambda.

**Comment by jaimeiniesta** [comment]
This repo is now deprecated in favor of https://github.com/jaimeiniesta/axe-puppeteer-lambda-http
